echo "Licensing icin assagidaki adimlara dikkat edilmelidir"
echo "flexlm dosyasinin icerisinde License.dat dosyasi olmalidir"
echo "License.dat dosyasina;"
echo "SERVER debian-MacBookAir 7C04D0D520E2 1702"
echo "DAEMON actlmgrd /home/debian/flexlm/actlmgrd"
echo "DAEMON mgcld /home/debian/flexlm/mgcld"
echo "VENDOR snpslmd /home/debian/flexlm/snpslmd"
echo "Yazilmalidir"
echo "-----------------------------------------------"
echo "licence islemi % /home/debian/microchip/ModelSimPro/modeltech/linuxacoem/mgls/bin/lmgrd -c /home/debian/flexlm/License.dat"
echo "-----------------------------------------------"
echo ".bashrc icerisinde % export PATH=/home/debian/microchip/Libero/bin:\ " 
echo "/home/debian/microchip/ModelsimPro/modeltech/linuxacoem:${PATH}"
echo "Eklenmelidir"
echo "-----------------------------------------------"
echo ".bashrc kaydedildikten sonra % source .bashrc komutu girilmelidir"
echo "-----------------------------------------------"
echo "% cd microchip/ModelSimPro/modeltech/linuxacoem/ directory'sine gidilip"
echo "./vsim yazilmalidir"
echo "-----------------------------------------------"
